"""airlines iata not unique

Revision ID: 0534491050dc
Revises: c8a17a7b20ca
Create Date: 2026-07-31 15:19:47.791982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0534491050dc'
down_revision: Union[str, Sequence[str], None] = 'c8a17a7b20ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airlines_iata'), table_name='airlines')
    op.create_index(op.f('ix_airlines_iata'), 'airlines', ['iata'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airlines_iata'), table_name='airlines')
    op.create_index(op.f('ix_airlines_iata'), 'airlines', ['iata'], unique=1)
    # ### end Alembic commands ###
