"""careers and schedules tables

Revision ID: 3c2eec61916f
Revises: 4944f5608460
Create Date: 2026-08-03 15:46:49.608705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2eec61916f'
down_revision: Union[str, Sequence[str], None] = '4944f5608460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_picture_path', sa.String(), nullable=False),
    sa.Column('base_icao', sa.String(length=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('current_airline_icao', sa.String(length=3), nullable=False),
    sa.Column('bank_balance', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_icao'], ['airports.icao'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['current_airline_icao'], ['airlines.icao'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_base_icao'), 'careers', ['base_icao'], unique=False)
    op.create_index(op.f('ix_careers_current_airline_icao'), 'careers', ['current_airline_icao'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('day_no', sa.Integer(), nullable=False),
    sa.Column('flight_index', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('departure_time_utc', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'current', 'future')", name='status_valid_option'),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'day_no', 'flight_index', name='unique_day_no_and_flight_index')
    )
    op.create_index(op.f('ix_schedules_career_id'), 'schedules', ['career_id'], unique=False)
    op.create_index(op.f('ix_schedules_route_id'), 'schedules', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_route_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_career_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_careers_current_airline_icao'), table_name='careers')
    op.drop_index(op.f('ix_careers_base_icao'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###
