"""aircraft families

Revision ID: 41bfd6e19deb
Revises: 0534491050dc
Create Date: 2026-07-31 15:47:18.601517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bfd6e19deb'
down_revision: Union[str, Sequence[str], None] = '0534491050dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.CheckConstraint("category IN ('mainline_jet', 'regional_jet', 'turboprop', 'business')", name='ck_aircraft_family_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_aircraft_family_id'), ['family_id'], unique=False)
        batch_op.create_foreign_key('fk_aircraft_family_id', 'aircraft_families', ['family_id'], ['id'])
        batch_op.drop_column('manufacturer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_aircraft_family_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_aircraft_family_id'))
        batch_op.drop_column('family_id')
    op.drop_table('aircraft_families')
    # ### end Alembic commands ###
