"""route synthetic data flags

Revision ID: 6baad77f868d
Revises: 41bfd6e19deb
Create Date: 2026-07-31 16:22:51.325906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6baad77f868d'
down_revision: Union[str, Sequence[str], None] = '41bfd6e19deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('flight_number_synthetic', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('routes', sa.Column('schedule_synthetic', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'schedule_synthetic')
    op.drop_column('routes', 'flight_number_synthetic')
    # ### end Alembic commands ###
