"""drop route departure time

Revision ID: 897a9ded0b7e
Revises: b7fc31151597
Create Date: 2026-08-01 12:05:25.835298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897a9ded0b7e'
down_revision: Union[str, Sequence[str], None] = 'b7fc31151597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'departure_time_utc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('departure_time_utc', sa.TIME(), nullable=False))
    # ### end Alembic commands ###
