"""airline logo flag

Revision ID: b7fc31151597
Revises: e07f08e722af
Create Date: 2026-07-31 16:41:49.751218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fc31151597'
down_revision: Union[str, Sequence[str], None] = 'e07f08e722af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airlines', sa.Column('has_logo', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airlines', 'has_logo')
    # ### end Alembic commands ###
