"""initial schema

Revision ID: c8a17a7b20ca
Revises: 
Create Date: 2026-07-31 14:53:32.974145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a17a7b20ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('icao_type', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('icao_type')
    )
    op.create_table('airlines',
    sa.Column('icao', sa.String(length=3), nullable=False),
    sa.Column('iata', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('icao')
    )
    op.create_index(op.f('ix_airlines_iata'), 'airlines', ['iata'], unique=True)
    op.create_table('airports',
    sa.Column('icao', sa.String(length=4), nullable=False),
    sa.Column('iata', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('icao')
    )
    op.create_index(op.f('ix_airports_iata'), 'airports', ['iata'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_icao', sa.String(length=3), nullable=False),
    sa.Column('origin_icao', sa.String(length=4), nullable=False),
    sa.Column('destination_icao', sa.String(length=4), nullable=False),
    sa.Column('aircraft_icao_type', sa.String(length=4), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('distance_nm', sa.Float(), nullable=False),
    sa.Column('departure_time_utc', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('distance_nm > 0', name='ck_route_distance_positive'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_route_duration_positive'),
    sa.CheckConstraint('origin_icao != destination_icao', name='ck_route_origin_ne_destination'),
    sa.ForeignKeyConstraint(['aircraft_icao_type'], ['aircraft.icao_type'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['airline_icao'], ['airlines.icao'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['destination_icao'], ['airports.icao'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['origin_icao'], ['airports.icao'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airline_icao', 'flight_number', name='uq_route_airline_flight_number')
    )
    op.create_index(op.f('ix_routes_aircraft_icao_type'), 'routes', ['aircraft_icao_type'], unique=False)
    op.create_index(op.f('ix_routes_airline_icao'), 'routes', ['airline_icao'], unique=False)
    op.create_index(op.f('ix_routes_destination_icao'), 'routes', ['destination_icao'], unique=False)
    op.create_index(op.f('ix_routes_origin_icao'), 'routes', ['origin_icao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_origin_icao'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_icao'), table_name='routes')
    op.drop_index(op.f('ix_routes_airline_icao'), table_name='routes')
    op.drop_index(op.f('ix_routes_aircraft_icao_type'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_airports_iata'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_iata'), table_name='airlines')
    op.drop_table('airlines')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
