"""route aircraft type synthetic flag

Revision ID: e07f08e722af
Revises: 6baad77f868d
Create Date: 2026-07-31 16:29:16.975826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07f08e722af'
down_revision: Union[str, Sequence[str], None] = '6baad77f868d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('aircraft_icao_type_synthetic', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'aircraft_icao_type_synthetic')
    # ### end Alembic commands ###
